mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt import views as jwt_views

# URLConf
urlpatterns = [
    # /lar/
    # Tudo o que começa por /lar/ é referenciado pelo polls.urls
    path('', include('polls.urls')),
    # /admin/
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

# URLConf
urlpatterns = [
    #  root
    path("", views.index, name='index'),

    # /register/
    path("register/", views.register_request, name="register"),
    
    # /login/
    path("login/", views.login_request, name="login"),

    # /lar/
    path("lar/", views.index_lares, name='index_lares'),

    # /equipas/
    path('equipa/', views.index_equipa, name='index_equipa'),

    # /produto/
    path('produto/', views.index_produto, name='index_produto'),

    # /visit/
    path('visit/', views.index_visit, name='index_visit'),

    # /info/
    path('info/', views.index_info, name='index_info.html')
]

polls/models.py
import datetime
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


# from rest_framework import serializers

# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = {'url', 'name', 'email'}


# Our model (table) lar has:
# ID - id do lar
# name - nome do lar
# owner - é uma foreign key para User, ou seja, é apenas um User que é associado a este lar como owner
# users - uma lista de utilizadores, com permissões a definir dentro do Django
class Lar(models.Model):
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User, related_name='owner', on_delete=CASCADE)
    users = models.ManyToManyField(User)
    def __str__(self):
        return self.name

# O modelo Produto contem:
# ID
# name - nome do produto
# price - preço do produto
# quantity - quantidade deste produto que existe em stock
class Produto(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField(default=0)
    quantity = models.IntegerField(default=0)
    def __str__(self):
        return self.name

# O modelo Equipa contem:
# ID
# name - nome desta equipa
# team_user - lista de utilizadores de uma equipa (membros desta)
class Equipa(models.Model):
    name = models.CharField(max_length=30)
    user = models.ManyToManyField(User)
    def __str__(self):
        return self.name

# O modelo de Visitas contem:
# ID 
# visit_team - O ForeignKey com Equipa, identifica a equipa responsável pela visita 
# visit_date - data da realização da visita
# description - uma breve descrição da visita
# lar - identifica um único lar visitado com o ForeignKey
# product - lista de produtos utilizados numa visita
# infected_users - lista de utilizadores dados como infetados numa visita
class Visita(models.Model):
    visit_team = models.ForeignKey(Equipa, on_delete=CASCADE)
    visit_date = models.DateField(null=False, blank=False)
    description = models.TextField(default='')
    lar = models.ForeignKey(Lar, on_delete=CASCADE)
    product = models.ManyToManyField(Produto)
    infected_users = models.ManyToManyField(User, blank=True,)
    def __str__(self):
        return self.description




# class Intervention(models.Model):
#     visited_lar = models.ForeignKey(Lar, on_delete=CASCADE)
#     used_product = models.ManyToManyField(Produto)
#     infected_user = models.ManyToManyField(User)
#     def __str__(self):
#         return self.visited_lar
   

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# My forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
    	model = User
    	fields = ("username", "email", "password1", "password2", "first_name", "last_name")

    def save(self, commit=True):
    	user = super(NewUserForm, self).save(commit=False)
    	user.email = self.cleaned_data['email']
    	if commit:
    		user.save()
    	return user

polls/views.py
from os import name
from typing import List
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.db.models.fields import EmailField
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required

# from django.http import Http404

from polls.models import Lar, Equipa, Visita, Produto, User

# Root View
def index(request):
    # Checks if user is authenticated, if not, redirects us to the login func
    if not request.user.is_authenticated:
        return render(request, "polls/login.html")

    # Receive all the objects inside a team
    equipas = Equipa.objects.all()
    
    # we create out dictionary, initially empty. we fill it with info from our teams
    context = {
        'index_list' : []
    }

    # Colocamos a lista de equipas
    # teams have name and a bunch of users
    # each user has id, username, name, email, and if it's staff
    for equipa in equipas: 
        index_json = {
            'name' : equipa.name,
            'users' : [{'id': u.id, 'username': u.username, 'name': u.first_name + ' ' + u.last_name, 
                        'email': u.email, 'is_staff': u.is_staff } for u in equipa.user.all()]
        }
        context['index_list'].append(index_json)
    
    # renders us to the  index page
    return render(request, 'polls/index.html')

def register_request(request):
    # we use POST for this register
    # we check if the method is POST, if it isn't we raise an error
    if request.method == "POST":
        # we create a form with POST
	    form = NewUserForm(request.POST)
        # if the form is valid, we save it and save a user
        # giving the message that the regist has been done successfuly
	    if form.is_valid():
		    user = form.save()
		    login(request, user)
		    messages.success(request, "Registration successful." )
		    # we redirect over to equipas
		    return redirect("/info/")
	    messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="polls/register.html", context={"register_form":form})


# method to log user in
def login_request(request):
    if request.user.is_authenticated:
        return render(request, "info/index_info.html")
    # we check to be sure the method is POST
    # if not, error
    if request.method == "POST":
        # we start a form with out request and our data, being this one the data of the user
        form = AuthenticationForm(request, data=request.POST)
        # if the form is valid we get the username and the password provided
        if form.is_valid():
        	username = form.cleaned_data.get('username')
        	password = form.cleaned_data.get('password')
        	user = authenticate(username=username, password=password)
        	if user is not None:
        		login(request, user)
        		messages.info(request, f"You are now logged in as {username}.")
        		# return redirect("index_equipa")
        		return redirect("/info/")
        	else:
        		messages.error(request,"Invalid username or password.")
        else:
        	messages.error(request,"Invalid username or password.")
    # we save our form as an AuthenticationForm, and render it
    form = AuthenticationForm()
    return render(request=request, template_name="polls/login.html", context={"login_form":form})



# Lar view
# Requires Login to access info
@login_required(login_url='/login/')
def index_lares(request):
    #if not request.user.is_authenticated:
    #    return redirect("/admin")

    lar_list = Lar.objects.all()
    #template = loader.get_template('polls/index_lares.html')

    # we start our dictionary as empty 
    context = {
        'lar_list' : []
    }
    
    # for each lar, we create a lar_json that has an id, name, owner
    # it also has a list of users, being those the lar users
    for lar in lar_list:
        lar_json = {
            'id' : lar.id,
            'name' : lar.name,
            'owner' : lar.owner,
            'users' : [{'id': u.id, 'username': u.username, 'name': u.first_name + ' ' + u.last_name, 
                        'email': u.email, 'is_staff': u.is_staff } for u in lar.users.all()]
        }
        # 
        context['lar_list'].append(lar_json)

    # return HttpResponse(template.render(context, request))
    return render(request, 'lares/index_lares.html', context)

# Equipa view
# requires login to access equipa
@login_required(login_url='/login/')
def index_equipa(request):
    equipa_list = Equipa.objects.all()
    # name = Equipa.objects.name

    context = {
        'equipa_list' : []
    }
    # for each equipa, we create a equipa_json that has an id, name
    # it also has a list of users, being those the equipa users
    for equipa in equipa_list:
        equipa_json = {
            'equipa_list': equipa_list,
            'id': equipa.id,
            'name': equipa.name,
            'user': [{'id': u.id, 'username': u.username, 'name': u.first_name + ' ' + u.last_name, 
                        'email': u.email, 'is_staff': u.is_staff } for u in equipa.user.all()]
        }
    context['equipa_list'].append(equipa_json)

    return render(request, 'equipas/index_equipa.html', context)

# Visit view
# requires login to access visits
@login_required(login_url='/login/')
def index_visit(request):
    # we create a visit with all the objects inside Visita
    visit_list = Visita.objects.all()
    #  keeps the number of actual infected on all the visits
    total_infected = 0

    context = {
        'visit_list' : []
    }

    for visit in visit_list:
        # This is a variable to help us count the infected users 
        number_infected = 0
        #if there's an user inside all the users inside visit
        # we increment the number of infecteds for a given visit
        for u in visit.infected_users.all():
            number_infected+=1
        # creating our json file for our users
        visit_json = {
            'id' : visit.id,
            'visit_team' : visit.visit_team,
            'visit_date' : visit.visit_date,
            'description' : visit.description,
            'lar' : visit.lar,
            # inserting products inside this variable for each product inside visit
            'product' : [{'name': p.name, 'price': p.price, 'quantity': p.quantity} for p in visit.product.all()],
            'infected_users' : number_infected,
        }
        # we append visit_json to our previous context, or our dictionary
        context['visit_list'].append(visit_json)

    return render(request, 'visitas/index_visit.html', context)

#Product view
@login_required(login_url='/login/')
def index_produto(request):
    product_list = Produto.objects.all()
    context = {
        'product_list' : []
    }
    # for each product inside our list of products, we just pass the name, price and quantity over to the html
    for product in product_list:
        product_json = {
            'name' : product.name,
            'price' : product.price,
            'quantity' : product.quantity,
        }
        context['product_list'].append(product_json)

    return render(request, 'produtos/index_produto.html', context)

def index_info(request):
    return render(request, 'info/index_info.html')

# def login_view(request):
#     username = request.POST['username']
#     password = request.POST['password']
#     user = authenticate(request, username=username, password=password)
#     if user is not None:
#         login(request, user)
#         return render(request, 'equipas/index_equipas.html')
#     else:
#         return HttpResponse('You got an error loggin in')
#         #return render(request, 'polls/index_lares.html')

polls/templates/equipas/index_equipa.html
<!-- <!DOCTYPE html> -->
<html>
<title>Team  Page</title>

<body>
    <div class="topnav">
        <a href="/lar/">Nursing Home</a>
        <a href="/produto/">Products</a>
        <a href="/visit/">Visits</a>
        <a class="active" href="/equipa/">Teams</a>
        <a href="/info/">About Us</a>
        <!-- <a href="">Requisições</a> -->
    </div>
<style>
    .topnav {
        background-color: #283838;
        overflow: hidden;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        position: fixed;
        z-index: 2;  
    }
    .topnav a{
        float: left;
        color: #ffffff;
        text-align: center;
        padding: 14px 16px;
        font-size: 17px;
        text-decoration: none;
        width: 150px;
    }
    .topnav a:hover{
        background-color: #463f3f;
        color: #96D4D4;
    }
    .topnav a.active{
        background-color: #96D4D4;
        color: black;
    }
</style>

<div class="center">
{% if equipa_list %}

    <div class="slide-container">
        <!--images with number and caption text--> 
        <div class="slideshow fade">
            <img src="https://docelar.com.pt/wp-content/uploads/2019/03/00276-2020-setembro-03-Doce-Lar-6325-1-scaled.jpg" alt="HTML5" style="width:100%">
        </div>
        <div class="slideshow fade">
            <img src="http://www.altominho.tv/site/wp-content/uploads/2020/10/Idoso-1.jpg" alt="HTML5" style="width:100%">
        </div>
        <div class="slideshow fade">
            <img src="https://docelar.com.pt/wp-content/uploads/2019/03/00188-2020-setembro-03-Doce-Lar-6237-scaled.jpg" alt="HTML5" style="width:100%">
        </div>
    </div>

    <!--Slide-content style-->
  <style>
    * {box-sizing:border-box}

    /* Slideshow container */
    .slide-container {
      max-width: 1000px;
      position: relative;
      margin: auto;
      text-align: center;
      padding-top: 46px;
    }
    
    /* Hide the images by default */
    .slideshow {
      display: none;
    }

    /* Fading animation */
    .fade {
    -webkit-animation-name: fade;
    -webkit-animation-duration: 1.5s;
    animation-name: fade;
    animation-duration: 1.5s;
    }
    
    @-webkit-keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
    }
      
    @keyframes fade {
        from {opacity: .4}
        to {opacity: 1}
    }
    </style>

    <script>
        var slideIndex = 0;
        showSlides();

        function showSlides() {
        var i;
        var slides = document.getElementsByClassName("slideshow");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) {slideIndex = 1}
        slides[slideIndex-1].style.display = "block";
        setTimeout(showSlides, 4000); // Change image every 2 seconds
        }
    </script>

<div class="text">
    <ul>
    {% for equipa in equipa_list %}
    <h1>{{ equipa.name}}</h1>
        <!-- <button><a href="{% url 'polls:index_visit' %}">Entrar</a></button> -->
       
        <table>
            <tr>
                <th>ID</th> 
                <th>Name</th>
            </tr>
            <tr>
                <td>{{ equipa.id }}</td>
                <td>{{ equipa.name }}</td>
                <!--{% for user in equipa_list %}-->
                <!--<td> {{ user.name}}</td>-->
                <!--{% endfor %}-->
            </tr>
            {% if equipa.users %}
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
            </tr>
            {% for user in equipa_list %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
            {% endif %}
        </table>
   {% endfor %}
    </ul>
{% else %}
    <p>No polls are available</p>
{% endif %}
</div>

<style>
    h1 {
        font-size: 30px;
        text-transform: uppercase;
    }
    h2{
        padding-left: 50px;
        font-size: 20px;
        color: #283838;
    }
    .text {
        text-align: left;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }
    table, th, td {
        border: 3px solid white;
        border-collapse: collapse;
        text-align: center;   
        padding: 15px 20px 20px 20px;  
        margin-left: auto;
        margin-right: auto;
    }
    th, td {
        background-color: #96D4D4;
    }
</style>
</div>

<div class="bottom"> 
    <p>Developed by: Patrícia Santos & João Carvalho</p>
</div>
<!--bottom style-->
<style>
    .bottom{
        background-color: black;
        padding: 16px 16px;
        color: white;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        font-size: 12;
        text-align: center;
        margin-top: 20px;
    }
</style>

<!--body style-->
<style>
    body {
        width: 800px;
        margin: 0 auto;
    }
</style>
</body>
</html> 